### ISSUE TITLE
Implement `salva_anagrafica` and `autocompleta_anagrafica`

### ISSUE THREAD

**Issue by melefabrizio** [fattureincloud/fattureincloud-php-sdk#108]
Currently Api v2 does not support the `salva_anagrafica` and `autocompleta_anagrafica` options on `IssuedDocument` endpoints to automatically save and fetch entity information, it would be very useful to implement it, as it makes transition from v1 to v2 much easier

**Comment by valmoz** [comment]
Hi @melefabrizio it is already in our [roadmap](https://trello.com/b/uAjGCOhL/fic-api-roadmap-overview).

I'll close this issue because it is not a PHP SDK issue, as it is API-related.
