### ISSUE TITLE
Custom template not listed

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/fattureincloud-php-sdk#112]
**Describe the bug**
With the command $fattureInCloud->info()->listTemplates() we can't see our custom template we created on Fatture in cloud web gui.

**Env info**
Please, provide us with the following details:
- PHP version 8.0
- PHP SDK version latest

**To Reproduce**
$fattureInCloud->info()->listTemplates()

**Expected behavior**
Show our custom templates

**Comment by valmoz** [comment]
Hi @Mattia-Marchiorato 
can you please try to perform the same operation on the [API Reference](https://developers.fattureincloud.it/api-reference/#get-/info/templates)? This will help us to understand if the problem is due to the SDK or to the APIs.

Thanks
Mauro

**Comment by Mattia-Marchiorato** [comment]
Hello @valmoz 

Same response from API
```json
{
  "data": [
    {
      "id": 10,
      "name": "New Standard S1",
      "supports_custom_taxable": true
    },
    {
      "id": 11,
      "name": "New Standard S2",
      "supports_custom_taxable": true
    },
    {
      "id": 12,
      "name": "New Professionisti P1",
      "supports_custom_taxable": true
    },
    {
      "id": 13,
      "name": "New Buste",
      "supports_custom_taxable": true
    },
    {
      "id": 14,
      "name": "New Professionisti P2",
      "supports_custom_taxable": true
    },
    {
      "id": 101,
      "name": "Clear lines",
      "supports_custom_taxable": true
    },
    {
      "id": 106,
      "name": "Minimalist",
      "supports_custom_taxable": true
    },
    {
      "id": 107,
      "name": "Squared",
      "supports_custom_taxable": true
    },
    {
      "id": 108,
      "name": "Modern",
      "supports_custom_taxable": true
    },
    {
      "id": 150,
      "name": "Bright Colors",
      "supports_custom_taxable": true
    },
    {
      "id": 660,
      "name": "DDT 1",
      "supports_custom_taxable": false
    },
    {
      "id": 663,
      "name": "FT Accompagnatoria 1",
      "supports_custom_taxable": false
    },
    {
      "id": 2821,
      "name": "Light Smoke",
      "supports_custom_taxable": true
    },
    {
      "id": 3053,
      "name": "Light Smoke - DDT (senza prezzi)",
      "supports_custom_taxable": false
    },
    {
      "id": 3054,
      "name": "Light Smoke - FT ACC",
      "supports_custom_taxable": true
    },
    {
      "id": 40170,
      "name": "Light Smoke - DDT (con prezzi)",
      "supports_custom_taxable": false
    }
  ]
}
```

Only default templates.

Thanks

MM

**Comment by valmoz** [comment]
@Mattia-Marchiorato 
sorry, you're right. The List Templates method is not company-scoped, so it cannot retrieve the custom templates.

You can retrieve the templates using the [GetIssuedDocumentPreCreateInfo](https://developers.fattureincloud.it/api-reference/#get-/c/-company_id-/issued_documents/info) and accessing the *data.templates_list* field.

Let us know if you can see your template using this method.

Thanks
Mauro

**Comment by Mattia-Marchiorato** [comment]
@valmoz ok, not the best solution but is working, now we solved the problem.

Thanks

MM
