### ISSUE TITLE
data.items_list.0.discount can't be null, discording with API Reference 

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/fattureincloud-php-sdk#116]
**Describe the bug**
POST https://api-v2.fattureincloud.it/c/company_id/issued_documents resulted in a 422 Unprocessable Entity response:
{"error":{"message":"Invalid request.","validation_result":{"data.items_list.0.discount":["The data.items list.0.discoun

From API Reference
discount: number┃null Discount percentual value.
But when is set to null we receive a 422

**Env info**
- PHP version 8.0
- PHP SDK version latest

**To Reproduce**
Create an invoice with discount null

**Expected behavior**
Creation of an invoice

**Comment by emajo** [comment]
Hi @Mattia-Marchiorato, thank you for reporting this error, we will fix the documentation removing null as an accepted value.

**Comment by Mattia-Marchiorato** [comment]
Hello @emajo 
We are using api v2 in production and before 5 of jenuary (or around that date) null was an accepted value, sid you changed the API? If yes is there any API change log?

Thanks

MM

**Comment by emajo** [comment]
Yes, we improved the validations of the fields items_list and payments_list, you can find our changelog [here](https://developers.fattureincloud.it/docs/CHANGELOG).

**Comment by Mattia-Marchiorato** [comment]
Ok thanks, there is a way to get notified about braking changes like this?
We are using the API in production and we missed like 10 invoice because of the improvement.

Thanks

MM

**Comment by emajo** [comment]
We currently don't have a system for notifying the developers, but braking changes like these will most likely not happen again.
