### ISSUE TITLE
Creare una fattura da cliente esistente

### ISSUE THREAD

**Issue by gotrens** [fattureincloud/fattureincloud-php-sdk#117]
Buongiorno

Purtroppo non trovo alcun riferimento su come creare una fattura con dati di un cliente esistente.

La vostra SDK prevede solo il setEntity per la creazione di nuovi clienti (se non sbaglio)

Nella vecchia versione c'era la funzione "autocompila_anagrafica" che non ritrovo qui

**Comment by valmoz** [comment]
Buongiorno.
chiudo questa issue, in quanto non è un problema sulla SDK ma solamente una richiesta di informazioni.

In ogni caso, come indicato sulla [guida alla creazione delle fatture](https://developers.fattureincloud.it/docs/guides/invoice-creation#1%EF%B8%8F%E2%83%A3-step-one-the-customer), al momento NON effettuiamo l'autocomplete sulle nostre API (quindi non solo sulla PHP SDK).
L'unico modo resta quello di recuperare il cliente utilizzando i metodi dedicati e passare i dettagli del cliente unitamente al suo ID.

Qualora dovesse avere ulteriori domande potrà aprire una nuova discussion sulla nostra [Community](https://github.com/fattureincloud/api/discussions)

Grazie
Mauro
