### ISSUE TITLE
`listPaymentMethods()` doesn't return `PaymentMethodDetails`

### ISSUE THREAD

**Issue by thugic** [fattureincloud/fattureincloud-php-sdk#118]
**Describe the bug**
When calling `InfoApi::listPaymentMethods()` the expected payload should carry a filled `details` key (when such object is populated). 
It returns a `details => null` instead:

```php
$infoApi->listPaymentMethods($companyId)->getData(); // Returns FattureInCloud\Model\PaymentMethod[]
```

When plucking out a `PaymentMethod` which has `details` set in company settings (on the web interface):
```
[
  "id" => 2047125,
  "name" => "Test",
  "is_default" => false,
  "default_payment_account" => null,
  "details" => null, // <-------------- This should not be `null` as it's filled correctly in the web interface
  "bank_iban" => null,
  "bank_name" => null,
  "bank_beneficiary" => null,
  "ei_payment_method" => null,
]
```

**Env info**
Please, provide us with the following details:
- PHP: 8.1
- PHP SDK version: latest as of the date the isse has been opened

**To Reproduce**
Please, share with us (if applicable):
Follow what's in `Describe the bug` section.

**Comment by thugic** [comment]
Also, it's a bummer that in V1 we could set throwaway ad-hoc payment methods in documents, and now in V2 we are enforced to use those persisted in the app.

Sometimes customers need for a one-time payment method which they won't reuse anymore, which makes it impossible with current API implementation (unless we keep storing payment methods and end up with an endless list of useless payment methods after some time) ...

**Comment by emajo** [comment]
Hi @thugic, if you make the list payment accounts call with our API Reference or postman the details field is populated as you expect?
Regarding the one-time payment methods we can discuss with the team about it.

Thanks,
Emanuele.
