### ISSUE TITLE
Field "email" is not returned on "issued_documents"

### ISSUE THREAD

**Issue by lucaele** [fattureincloud/fattureincloud-php-sdk#120]
Hi,
on "issued_documents" with type = invoice,
"entity.email" is it not inserted on document.
This is the only one field of entity block with this problem.

Someone fixed this problem?

**Comment by emajo** [comment]
Hi, if you need to set the email field you must create the client and pass its id in the entity.id field creating the document, [here](https://github.com/fattureincloud/api/discussions/226) you can find a discussion about it.

Thanks,
Emanuele.
