### ISSUE TITLE
create issued document with vat model retreived from endpoint

### ISSUE THREAD

**Issue by Mattia-Marchiorato** [fattureincloud/fattureincloud-php-sdk#123]
**Describe the bug**
Invoice creation issue

**To Reproduce**
Get the vatType "GET /c/{company_id}/info/vat_types" with id 0 (for italy), then use the VatType object as it is to create an invoice.

 Client error: `POST https://api-v2.fattureincloud.it/c/9999999/issued_documents` resulted in a `422 Unprocessable Entity` response:
{"error":{"message":"Invalid request.","validation_result":{"data.items_list.0.vat.notes":["The data.items list.0.vat.no (truncated...)
 {"exception":"[object] (FattureInCloud\\ApiException(code: 422): [422] Client error: `POST https://api-v2.fattureincloud.it/c/99999999/issued_documents` resulted in a `422 Unprocessable Entity` response:
{\"error\":{\"message\":\"Invalid request.\",\"validation_result\":{\"data.items_list.0.vat.notes\":[\"The data.items list.0.vat.no (truncated...)
 at /var/www/html/vendor/fattureincloud/fattureincloud-php-sdk/lib/Api/IssuedDocumentsApi.php:206)
 
**Expected behavior**
Invoice creation or an error message not truncated.

**Comment by valmoz** [comment]
Hi @Mattia-Marchiorato 
unfortunately, this is the default behaviour of the Guzzle HTTP Client, that's used by the PHP SDK to contact our REST APIs.

Luckily, our SDK accepts a Guzzle Client as parameter of the APIs constructors, making it possible to use Guzzle's [BodySummarizer](https://github.com/guzzle/guzzle/blob/master/src/BodySummarizer.php) to change the default truncating length. 

The BodySummarizer must be inserted in the [Middleware](https://github.com/guzzle/guzzle/blob/master/src/Middleware.php) called _httpErrors_.

You can try to initialize the API as follows: 

```php
use FattureInCloud\Api\UserApi;
use FattureInCloud\Configuration;
use GuzzleHttp\Client;

$stack = new HandlerStack(Utils::chooseHandler());
$stack->push(Middleware::httpErrors(new BodySummarizer(5000)), 'http_errors');
$stack->push(Middleware::redirect(), 'allow_redirects');
$stack->push(Middleware::cookies(), 'cookies');
$stack->push(Middleware::prepareBody(), 'prepare_body');
$client = new Client(['handler' => $stack /* other options here */ ]);

$config = FattureInCloud\Configuration::getDefaultConfiguration()->setAccessToken($accessToken);

$userApi = new FattureInCloud\Api\UserApi(
    $client,
    $config
);
```

if you want to change the behavior of BodySummarizer, Guzzle offers also a [BodySummarizerInterface](https://github.com/guzzle/guzzle/blob/master/src/BodySummarizerInterface.php) that you can use to customize the obtained result as you prefer.

Below you can find some useful links:
- [Original issue on Guzzle GitHub repo](https://github.com/guzzle/guzzle/issues/2185#issuecomment-800293420)
- [Guzzle Handlers and Middlewares](https://docs.guzzlephp.org/en/stable/handlers-and-middleware.html)

We would prefer to not force this behaviour to our SDK, and let the developer choose the best solution for the specific use case. For sure we can add a note in the documentation if it could be useful.

Let us know if this solves the issue.

Thanks
Mauro

**Comment by Mattia-Marchiorato** [comment]
Hello @valmoz ,

Ok perfect, thanks.

MM
