### ISSUE TITLE
Disabilitare "Mostra scadenze" in creazione Proforma

### ISSUE THREAD

**Issue by christiancannata** [fattureincloud/fattureincloud-php-sdk#132]
**Describe the bug**
Come si può in fase di creazione proforma togliere il flag su "Mostra scadenze" nella tab "Personalizzazione"?

<img width="404" alt="Screenshot 2023-11-07 alle 20 11 55" src="https://github.com/fattureincloud/fattureincloud-php-sdk/assets/4604959/86065793-3bc7-4389-a359-0d60a32be191">

**Comment by emajo** [comment]
Ciao @christiancannata, le chiedo gentilmente di postare questa domanda nelle nostre [discussions](https://github.com/fattureincloud/api/discussions), in quanto si tratta di una domanda generica sulle api che può tornare utile anche ad altri utenti.

Grazie,
Emanuele.
