### ISSUE TITLE
Fatture - Implementazione sconto con importo fisso sulla singola riga di dettaglio

### ISSUE THREAD

**Issue by g-scalvini** [fattureincloud/fattureincloud-php-sdk#135]
Buongiorno a tutti,
nella rappresentazione tabellare del tracciato Fattura PA, è indicato che, all'interno degli N elementi della sezione "2.2 DatiBeniServizi" per il blocco 2.2.1.10 ScontoMaggiorazione, è necessario specificare almeno uno tra gli elementi "2.2.1.10.2 Percentuale" o "2.2.1.10.3 Importo", fornendo quindi la possibilità di inserire uno sconto percentuale oppure uno sconto con importo fisso:
> Se valorizzato, viene controllato che esista almeno uno dei due elementi 2.2.1.10.2 Percentuale e 2.2.1.10.3 Importo

All'interno dell'SDK, nella classe IssuedDocumentItemsListItem, il campo "discount" è unico e di fatto corrisponde al campo di sconto percentuale, non permettendo quindi di inserire uno sconto con importo fisso.

L'introduzione dello sconto con importo fisso sulla singola riga di dettaglio è prevista come futura implementazione?

Grazie

**Comment by valmoz** [comment]
Buongiorno @g-scalvini questa non è una issue relativa alla PHP SDK, ma si tratta di una domanda generica di utilizzo di API.
Le chiederei quindi di aprire una discussion sulla nostra [Community](https://github.com/fattureincloud/api/discussions) con lo stesso contenuto.

Grazie
Mauro
