### ISSUE TITLE
Errore di non autorizzazione 401 lista clienti

### ISSUE THREAD

**Issue by piccio85** [fattureincloud/fattureincloud-php-sdk#136]
**Describe the bug**
Dal 9 di gennaio quando provo ad accedere alla lista clienti ottengo un errore "401 non autorizzato"

**Env info**
- PHP 8.0.30
- PHP SDK 2.0.24

**To Reproduce**
Eseguo una chiamata per avere la lista dei clienti ma ottengo un errore 401

```php

$companies = $userInstance->listUserCompanies();
if (empty($companies->getData()->getCompanies())){
return;
}
$companyId = $companies->getData()->getCompanies()[0]->getId();

$cont_pagina = 1;
$listaClienti = [];

	do {
		try {
			$resClienti = $clientInstance->listClients($companyId, null, null, null, $cont_pagina, 100);
		} catch (Exception $e) {
return;
}

``` 

[401] Client error: `GET https://api-v2.fattureincloud.it/c/944984/entities/clients?page=1&per_page=100` resulted in a `401 Unauthorized` response:
{"error":"unauthorized","error_description":"The given user is not authorized to use this application."}

Mostro alcuni screenshot:
![image](https://github.com/fattureincloud/fattureincloud-php-sdk/assets/12586165/7cc8ae13-73c6-40fc-a0c1-a952f0b6da2c)

![image](https://github.com/fattureincloud/fattureincloud-php-sdk/assets/12586165/355a1d40-b843-4afe-bf39-c4911ffe0fd1)

![image](https://github.com/fattureincloud/fattureincloud-php-sdk/assets/12586165/e3beb973-24c5-489e-97fc-e4fe2db3754d)

**Comment by valmoz** [comment]
Buongiorno @piccio85 
chiudo questa discussione in quanto questa non è una issue relativa alla PHP SDK.
Le consiglio di contattare il nostro supporto clienti, o in alternativa di aprire una nuova discussion sulla nostra [community](https://github.com/fattureincloud/api/discussions?discussions_q=).

Grazie
Mauro
