### ISSUE TITLE
Fatture - Campo 2.1.1.1 - TipoDocumento

### ISSUE THREAD

**Issue by g-scalvini** [fattureincloud/fattureincloud-php-sdk#137]
Buongiorno a tutti,
all'interno di un'integrazione custom tra uno dei nostri SW e Fatture in Cloud abbiamo la necessità di specificare, nella chiamata di creazione di una fattura (POST /c/{company_id}/issued_documents), il campo 2.1.1.1 - TipoDocumento.

Tale campo è modificabile da interfaccia FiC nella sezione "Attributi avanzati" del blocco Fatturazione elettronica mentre all'interno del SDK o della documentazione API non riesco a trovare riferimenti al campo in questione.
Mi aspettavo di trovarlo nella classe FattureInCloud\Model\IssuedDocumentEiData ma vedo che non è presente.

Potreste indicarmi se tale campo è esposto nella rotta API oppure se ne è prevista la futura implementazione?

Grazie

**Comment by valmoz** [comment]
Buongiorno @g-scalvini questa non è una issue relativa alla PHP SDK, ma si tratta di una domanda generica di utilizzo di API.
Le chiederei quindi di aprire una discussion sulla nostra [Community](https://github.com/fattureincloud/api/discussions) con lo stesso contenuto.

Grazie
Mauro
