### ISSUE TITLE
Error on fetchToken with oauth2

### ISSUE THREAD

**Issue by gpstiip88** [fattureincloud/fattureincloud-php-sdk#87]
**Describe the bug**
Getting error when use OAuth2 fetchToken method.

**Env info**
- PHP version: 7.4.27
- PHP SDK version: 2.0.13 

**To Reproduce**
Example code
```
$code = request()->code;
$redirectUri = "http://localhost:8000/api/grant";
$oauth = new OAuth2AuthorizationCodeManager("CLIENT_ID", "CLIENT_SECRET", $redirectUri);
$tokenObj = $oauth->fetchToken($code);
$accessToken = $tokenObj->getAccessToken();
$refreshToken = $tokenObj->getRefreshToken();
```

- Error status and message
Client error: `POST https://api-v2.fattureincloud.it/oauth/token` resulted in a `400 Bad Request` response:
{"error":"invalid_request","error_description":"The grant type field is required."}
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://api-v2.fattureincloud.it/oauth/token` resulted in a `400 Bad Request` response:
{\"error\":\"invalid_request\",\"error_description\":\"The grant type field is required.\"}

**Expected behavior**
Working fetchToken.

**Additional context**
I think the problem is in the method fetchToken at line 176 of OAuth2AuthorizationCodeManager.php, where the `$body` not includes key 'json', like it is described on Vanilla documentation (https://developers.fattureincloud.it/docs/authentication/code-flow/vanilla-code#3%EF%B8%8F%E2%83%A3-obtain-the-access-token)

**Comment by emajo** [comment]
Hi, 
that was actually a problem we had in the older releases of the package, we solved it in the last release ([2.0.14](https://packagist.org/packages/fattureincloud/fattureincloud-php-sdk)), so you will just need to update your dependency.

Let us know if this fixes your issue,
Thanks,
Emanuele
