### ISSUE TITLE
Invalid value 'manual_accepted' for 'ei_status'

### ISSUE THREAD

**Issue by mfrascati** [fattureincloud/fattureincloud-php-sdk#88]
**Describe the bug**
I valori di stato documento `manual_accepted` e (suppongo) `manual_rejected` non sono visti come validi

**Env info**
Php 7.4
sdk v2.0.13

**To Reproduce**
Nel recuperare l'elenco delle ultime fatture emesse:

```
$apiInstance = new IssuedDocumentsApi(new Client(), $this->config);
$all = $apiInstance->listIssuedDocuments($this->companyId, IssuedDocumentType::INVOICE, "id,ei_status,date", null, "-date", null, 10)->getData();
```

<img width="693" alt="image" src="https://user-images.githubusercontent.com/2734747/179516627-b20cfa35-b24a-402b-838f-bb3cd2200cb2.png">

**Comment by emajo** [comment]
Ciao @mfrascati, innanzitutto grazie per la segnalazione, effettivamente era un problema dell'sdk, abbiamo rilasciato la versione [2.0.15](https://packagist.org/packages/fattureincloud/fattureincloud-php-sdk) che risolve questo problema.

Grazie,
Emanuele
