### ISSUE TITLE
not working after install via composer

### ISSUE THREAD

**Issue by pws2016** [fattureincloud/fattureincloud-php-sdk#90]
**Describe the bug**
I install the package via composer  and not work!
How i can add in my code the library (to replace require_once(__DIR__ . '/vendor/autoload.php'); )? 
Must be have this line use FattureIncloud/xxxxxx

**Comment by emajo** [comment]
Hi @pws2016 I don't understand what you are trying to do, what's wrong with the 
`require_once(__DIR__ . '/vendor/autoload.php');`?

**Comment by pws2016** [comment]
i mean how can use Namespace?

**Comment by emajo** [comment]
What you can do is 

`<?php
require_once(__DIR__ . '/vendor/autoload.php');

use FattureInCloud\Configuration;
use FattureInCloud\Api\ArchiveApi;
...`

is this what you are looking for?

**Comment by valmoz** [comment]
Hi @pws2016 

Please, note that this is NOT the right place to ask how to do things with our SDKs. You should create new discussions [on our Community page.](https://github.com/fattureincloud/api/discussions)
The Issues category of this repo should only be used to require help with a bug in our SDK code.

Thanks,
Mauro
