### ISSUE TITLE
Fields created_at and updated_at not returned

### ISSUE THREAD

**Issue by itajackass** [fattureincloud/fattureincloud-php-sdk#92]
I tried to use method: ReceivedDocumentsApi->listReceivedDocuments to retrieve all expenses (in "detailed" mode) but fields "created_at" and "updated_at" are not returned.

If I use API REFERENCE web tools from: https://developers.fattureincloud.it/api-reference, both fields are returned correctly

**Comment by itajackass** [comment]
See my pull request: https://github.com/fattureincloud/fattureincloud-php-sdk/pull/93

**Comment by backloop-biz** [comment]
Sorry I have the same issue for invoice, expence, ecc also using the last version of SDK.
What's the detailed mode of listing?

**Comment by valmoz** [comment]
Hi @backloop-biz,
you should check this guide: [Customize response](https://developers.fattureincloud.it/docs/basics/additional-capabilities/customize-response)
The "fieldset" is a query string parameter that lets you select a predefined set of fields that must be returned; it can be set to "detailed" to return more parameters than the default response.

Also, you can check the PHP SDK Documentation (search on the Readme file) to find an example of how to use the fieldset in list requests; for example, the guide for [List Clients](https://github.com/fattureincloud/fattureincloud-php-sdk/blob/master/docs/Api/ClientsApi.md#listclients) method.

As a side note: this is NOT an issue with the PHP SDK, for generic guidance questions like this one you should open a discussion on our [Community](https://github.com/fattureincloud/api/discussions?discussions_q=) instead.

Thanks
Mauro
