### ISSUE TITLE
Entity senza chiave primaria?

### ISSUE THREAD

**Issue by ventoh** [fattureincloud/fattureincloud-php-sdk#94]
Salve, ho una domanda: come è possibile che ci siano alcune entity (associate a fatture) senza l'id. Qual è la chiave primaria su cui fare affidamento? Posso usare il name?
Grazie.

**Comment by valmoz** [comment]
Buongiorno,
le consiglio di scrivere questa domanda sulla nostra [community](https://github.com/fattureincloud/api/discussions), dove sicuramente otterrà risposta.

Questa sezione è dedicata solo alle issues della PHP SDK.

Grazie
Mauro
