### ISSUE TITLE
Modify Issued Document fails without emitting anything

### ISSUE THREAD

**Issue by melefabrizio** [fattureincloud/fattureincloud-php-sdk#98]
**Describe the bug**
A call to `$documentsApi->modifyIssuedDocument` with malformed parameters fails silently without emitting warnings, errors, or throwing exceptions

**Env info**
- PHP 7.2
- SDK 2.0.16

**To Reproduce**
- `$result = $documentsApi->modifyIssuedDocument($this->company_id, $document_id, $request)->getData();`, where the request is created with some invalid parameters (eg: adding/deleting/updating items without also updating the payment amount)

**Expected behavior**
An `ApiException` is thrown with, for instance,`"Il totale dei pagamenti non corrisponde al totale da pagare."` as a message.

**Additional context**
Also, it would be very convenient to have the `fix_payments` options also in the modifying requests.

**Comment by valmoz** [comment]
Hi @melefabrizio were you able to solve your problem?

**Comment by melefabrizio** [comment]
Hi, the solution was to dive into the library, log the error coming from the api, and then fixing the payload according to the error. 

The incriminated method is `IssuedDocumentsApi::modifyIssuedDocumentWithHttpInfo`:
```php

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\FattureInCloud\Model\ModifyIssuedDocumentResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\FattureInCloud\Model\ModifyIssuedDocumentResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\FattureInCloud\Model\ModifyIssuedDocumentResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }
```

To get the actual error I had to add a `default` block to the switch, and that's where I found the payments problem stated in the issue.
